import { GoogleGenAI } from '@google/genai';
import { ai } from '../geminiClient';

const UPLOAD_DIR = "./upload_files";
const THUMB_DIR = "./thumbnails";
const MODEL_NAME = "gemini-3.5-flash-lite";

if (!Bun.env.GEMINI_API_KEY) {
  console.warn("GEMINI_API_KEY is not set in environment variables.");
}

export interface GenerateOptions {
  model?: string;
  systemInstruction?: string;
  temperature?: number;
}

export async function generateGeminiContent(
  prompt: string,
  options: GenerateOptions = {}
): Promise<string> {
  //const modelName = options.model || "gemini-2.5-flash";

  console.log("Gemini prompt: " + prompt + " model: " + MODEL_NAME);

  try {
    
    const ai = new GoogleGenAI({ apiKey: Bun.env.GEMINI_API_KEY });
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: {
        systemInstruction: "You are a secure, high-performance AI assistant operating on a Bun runtime backend.",
        temperature: 0.7,
      },
    });

    return response.text || "No response generated.";
  } catch (error) {
    console.error("[Gemini Client Error]", error);
    throw new Error(`Failed to generate content from model ${MODEL_NAME}`);
  }
}

export default async function askGemini(ai: GoogleGenAI, promptText: string): Promise<string> {
    try {
        console.log("Gemini prompt: " + promptText);

        const response = await ai.models.generateContent({
            model: MODEL_NAME,
            contents: promptText,
        });

        console.log(response.text);

        return response.text || "";

    } catch (error) {
        console.error("Error communicating with Gemini:", error);
        return "";
    }
}


export async function generateChatResponse(prompt: string, systemInstruction?: string): Promise<string> {
  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: {
        systemInstruction: systemInstruction || "You are a secure, high-performance AI assistant operating on a Bun runtime backend.",
        temperature: 0.7,
      }
    });

    return response.text || "No response generated.";
  } catch (error) {
    console.error("[Gemini AI Error]", error);
    throw new Error("AI generation failed.");
  }
}


export async function askGeminiImageQuestion(ai: GoogleGenAI, promptText: string, imageFile: Bun.Image): Promise<string> {
    try {
        const response = await ai.models.generateContent({
            model: MODEL_NAME,
            // "Analyze this image and describe what you see in detail."
            contents: [
                { text: promptText},
                {
                    inlineData: {
                        data: await imageFile.toBase64(),
                        //mimeType: (await imageFile.metadata())
                        //metadata: await imageFile.metadata(),
                    },
                },
            ],
        });
        return response.text || "";
    } catch (error) {
        console.error("Error communicating with Gemini:", error);
        return ""; 
    }
}

//NOTE: uncomment and test
export async function segmentGeminiImage(ai: GoogleGenAI, promptText: string, imageFile: Bun.Image): Promise<string> {
    try {
        /*
        const response = await 
                ai.models.segmentImage({
            model:  'gemini-3.5-flash-lite',
            source:
        },
        config: {
        // Options include 'foreground', or specific object types depending on the task
        mode: 'foreground', 
      },
        })
        
        // Extract the raw image bytes of the generated mask
        const maskBase64 = response?.generatedMasks?.[0]?.mask?.imageBytes;

        if (maskBase64) {
        // Save the resulting mask to disk
        const outputBuffer = Buffer.from(maskBase64, 'base64');
        fs.writeFileSync('output_mask.png', outputBuffer);
        console.log('Image segmentation successful! Mask saved to output_mask.png');
        } else {
        console.log('o mask was generated by the model.');
        }

        */
        return "";
    } catch (error) {
        console.error("Error communicating with Gemini:", error);
        return ""; 
    }
}

// TODO:get image type => Change mimeType to be dynamic 
export async function analyseGeminiBase64(ai: GoogleGenAI, promptText: string, imageFile: Bun.Image): Promise<string> {
    console.log("Gemini prompt: " + promptText);
    const response = await ai.models.generateContent({
        model: MODEL_NAME,
        contents: [
            promptText,
            {
                inlineData: {
                    mimeType: 'image/png',
                    data: await imageFile.toBase64() || "",
                }
            }
        ]
    })
    return response.text || "";
}





    // JSON
    /*
    // Call the Google AI Studio developer endpoint directly
    //const url = `https://googleapis.com`;
    const url = "https://generativelanguage.googleapis.com/v1beta/interactions"; //

    const response = await fetch(url, {
        method: "POST",
        headers: myHeaders,
        body: JSON.stringify({
            model: "gemini-3.6-flash",
            input: prompt
        })
    });
    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Gemini API Error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    console.log(data);
*/



/*
    const ai = new GoogleGenAI({
        apiKey: process.env.GEMINI_API_KEY,
        vertexai: false,
        //googleAuthOptions: { apiKey: process.env.GEMINI_API_KEY },
        httpOptions: {
            // Explicitly forces the SDK to hit the standard developer AI Studio servers
            baseUrl: 'https://generativelanguage.googleapis.com',
            headers: {
                'x-goog-api-key': process.env.GEMINI_API_KEY || ''
            }
        }
    });
*/
